version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: temperinho-app-prod
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./.env:/var/www/.env
      - storage_prod:/var/www/storage
    networks:
      - temperinho-network
    depends_on:
      - db
      - meilisearch
      - redis

  nginx:
    image: nginx:alpine
    container_name: temperinho-nginx-prod
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - app_code:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - temperinho-network
    depends_on:
      - app

  db:
    image: postgres:15-alpine
    container_name: temperinho-db-prod
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    networks:
      - temperinho-network

  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: temperinho-meili-prod
    restart: unless-stopped
    environment:
      - MEILI_MASTER_KEY=${MEILISEARCH_KEY}
      - MEILI_ENV=production
    volumes:
      - meilidata_prod:/data.ms
    networks:
      - temperinho-network

  redis:
    image: redis:alpine
    container_name: temperinho-redis-prod
    restart: unless-stopped
    networks:
      - temperinho-network

networks:
  temperinho-network:
    driver: bridge

volumes:
  app_code:
  storage_prod:
  pgdata_prod:
    driver: local
  meilidata_prod:
    driver: local
