version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: site-receitas-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - site-receitas-network
        depends_on:
            - db
            - meilisearch

    nginx:
        image: nginx:alpine
        container_name: site-receitas-nginx
        restart: unless-stopped
        ports:
            # Mapeia as portas padrão HTTP e HTTPS
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/ssl:/etc/nginx/ssl
        networks:
            - site-receitas-network
        depends_on:
            - app

    # Serviço do Banco de Dados PostgreSQL
    db:
        image: postgres:15-alpine
        container_name: site-receitas-db
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE:-laravel}
            POSTGRES_USER: ${DB_USERNAME:-user}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - site-receitas-network

    # Serviço do Meilisearch
    meilisearch:
        image: getmeili/meilisearch:latest
        container_name: site-receitas-meili
        restart: unless-stopped
        ports:
            - "7700:7700"
        volumes:
            - meilidata:/data.ms
        networks:
            - site-receitas-network

    # Serviço do Redis
    redis:
        image: redis:alpine
        container_name: site-receitas-redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - site-receitas-network

networks:
    site-receitas-network:
        driver: bridge

volumes:
    pgdata:
        driver: local
    meilidata:
        driver: local
